import { useEffect, useState } from "react";
import { CheckCircle2, Sparkles, Verified } from "lucide-react";
import { useAuth } from "../context/AuthContext";
import { reportsAPI } from "../services/api";

function Approvals() {
  const { activeProject } = useAuth();
  const [reports, setReports] = useState([]);
  const [currentReport, setCurrentReport] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [action, setAction] = useState("");
  const [comment, setComment] = useState("");

  async function fetchPendingReports() {
    if (!activeProject) { setLoading(false); return; }
    try {
      setLoading(true);
      const res = await reportsAPI.list(activeProject._id);
      const allReports = res.data?.reports || res.data || [];
      const pending = allReports.filter((r) => r.status === "PENDING_REVIEW");
      setReports(pending);
      setCurrentReport(pending[0] || null);
      setError(null);
    } catch (err) {
      console.error("[Approvals] Fetch failed:", err.message);
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    fetchPendingReports();
  }, [activeProject]);

  async function handleDecision(decisionStatus) {
    if (!activeProject || !currentReport) return;
    try {
      setAction(`Submitting ${decisionStatus.toLowerCase()} decision...`);
      if (decisionStatus === "APPROVED") {
        await reportsAPI.approve(activeProject._id, currentReport._id, {
          status: "APPROVED",
          reviewComment: comment || "Approved by human-in-the-loop operator."
        });
        setAction("Report approved successfully!");
      } else {
        await reportsAPI.reject(activeProject._id, currentReport._id, {
          status: "REJECTED",
          reviewComment: comment || "Rejected/Revision requested."
        });
        setAction("Report rejected/revision requested.");
      }
      setComment("");
      // Re-fetch pending reports
      await fetchPendingReports();
    } catch (err) {
      console.error("[Approvals] Decision submission failed:", err.message);
      setAction(`Error: ${err.message}`);
    }
  }

  return (
    <main className="approval-page">
      <header className="approval-header">
        <div>
          <p className="workspace-label"><Verified size={14} /> Human-in-the-loop Review</p>
          <h1>Inspection Note Authorization</h1>
        </div>
        {currentReport && (
          <div className="approval-actions">
            <button className="approval-button revision" type="button" onClick={() => handleDecision("REJECTED")}>
              Request Revision
            </button>
            <button className="approval-button reject" type="button" onClick={() => handleDecision("REJECTED")}>
              Reject
            </button>
            <button className="approval-button approve" type="button" onClick={() => handleDecision("APPROVED")}>
              <CheckCircle2 size={17} /> Approve Note
            </button>
          </div>
        )}
      </header>

      {action && <div className="approval-feedback" role="status">{action}</div>}
      {error && <div className="approval-feedback" role="alert" style={{ color: "#ef8e84" }}>Error: {error}</div>}

      {loading ? (
        <p style={{ color: "#8f7768", padding: "24px", textAlign: "center", fontFamily: "'JetBrains Mono', monospace", fontSize: "11px" }}>Loading pending authorizations…</p>
      ) : !currentReport ? (
        <div className="approval-layout" style={{ justifyContent: "center", alignItems: "center", minHeight: "300px" }}>
          <section className="draft-panel" style={{ textAlign: "center", padding: "48px 24px" }}>
            <Verified size={48} style={{ color: "#ffb784", marginBottom: "16px", opacity: 0.8 }} />
            <h2>All Reports Authorized</h2>
            <p style={{ color: "#8f7768", marginTop: "8px" }}>There are no reports currently awaiting human-in-the-loop authorization.</p>
          </section>
        </div>
      ) : (
        <div className="approval-layout">
          <section className="draft-panel">
            <div className="draft-heading">
              <span>Draft Output</span>
              <b><Sparkles size={13} /> Generated by Sovara</b>
            </div>
            <article className="draft-content">
              <h2>{currentReport.title}</h2>
              <p className="draft-meta">
                Date: {new Date(currentReport.createdAt).toLocaleDateString()} | Inspector: {currentReport.createdBy?.name || "System Admin"}
              </p>
              
              {currentReport.summary && (
                <p className="citation" style={{ marginBottom: "20px" }}>
                  <mark title="Report Summary">{currentReport.summary}</mark>
                </p>
              )}

              {currentReport.findings && currentReport.findings.length > 0 && (
                <div style={{ marginBottom: "24px" }}>
                  <h3 style={{ fontSize: "15px", textTransform: "uppercase", color: "#ffb784", letterSpacing: "0.05em", marginBottom: "8px" }}>Findings</h3>
                  {currentReport.findings.map((f, idx) => (
                    <div key={idx} style={{ marginBottom: "12px", borderBottom: "1px solid #2e2926", paddingBottom: "12px" }}>
                      <h4 style={{ margin: "0 0 4px", fontSize: "14px", color: "#eae1db" }}>{f.title}</h4>
                      <p style={{ margin: 0, fontSize: "13px", color: "#dbc2b2" }}>{f.content}</p>
                    </div>
                  ))}
                </div>
              )}

              {currentReport.recommendations && currentReport.recommendations.length > 0 && (
                <div className="recommendation">
                  <h3>Actionable Recommendations</h3>
                  {currentReport.recommendations.map((r, idx) => (
                    <div key={idx} style={{ marginBottom: "8px" }}>
                      <p style={{ fontWeight: 600, margin: "0 0 2px" }}>{r.title}</p>
                      <p style={{ margin: 0 }}>{r.content}</p>
                    </div>
                  ))}
                </div>
              )}

              <div style={{ marginTop: "24px" }}>
                <label style={{ display: "block", fontSize: "12px", textTransform: "uppercase", color: "#8a8278", marginBottom: "8px" }}>Review Comments / Feedback</label>
                <textarea
                  value={comment}
                  onChange={(e) => setComment(e.target.value)}
                  placeholder="Enter comments to attach to this review decision (optional)..."
                  style={{
                    width: "100%",
                    minHeight: "80px",
                    background: "#1c1815",
                    border: "1px solid #2e2926",
                    borderRadius: "4px",
                    color: "#eae1db",
                    padding: "10px",
                    resize: "vertical"
                  }}
                />
              </div>
            </article>
          </section>

          <aside className="evidence-column">
            <section className="confidence-card">
              <h2>Analysis Confidence</h2>
              <Confidence label="Structural Assessment" value="94%" width="94%" />
              <Confidence label="Thermal Anomaly Verification" value="78%" width="78%" muted />
            </section>
          </aside>
        </div>
      )}
    </main>
  );
}

function Confidence({ label, value, width, muted }) {
  return <div className="confidence-row"><div><span>{label}</span><b className={muted ? "muted" : ""}>{value}</b></div><div className="confidence-track"><i className={muted ? "muted" : ""} style={{ width }} /></div></div>;
}

export default Approvals;
